import = [
    "~/.config/alacritty/themes/rose-pine-dawn.toml"
]

live_config_reload = true

[font]
size = 16.0

[font.normal]
family = "DankMono"
style = "Regular"

[window]
padding = { x = 30, y = 30 }
opacity = 0.88

[colors]
transparent_background_colors = true
