# Oh My ZSH Config
# ----------------

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh


# User Settings
# -------------

export TERM="screen-256color" 


# Aliases
# -------

# Programs
alias vim="nvim"
alias c="clear"

# Changing "ls" to "exa"
alias la='exa -al --color=always --group-directories-first' # my preferred listing
alias ls='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing

# Changing "cat" to "bat"
alias cat="bat"

# Git
alias addall='git add .'
alias branch='git branch'
alias checkout='git checkout'
alias clone='git clone'
alias commit='git commit -m'
alias fetch='git fetch'
alias pull='git pull origin'
alias push='git push origin'
alias stat='git status'  # 'status' is protected name so using 'stat' instead

# Tmux
alias tml="tmux list-sessions"
alias tma="tmux attach-session -t"
alias tmn="tmux new -s"


# Path
# ----

export PATH=$PATH:~/bin
export PATH=$PATH:~/.local/bin
