import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]

live_config_reload = true

[font]
size = 12.0
offset = { y = 10 }

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Regular"

[window]
padding = { x = 20, y = 20 }
opacity = 0.8

[colors]
transparent_background_colors = true
