import = [
    "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
]

live_config_reload = true

[font]
size = 11.0

[font.normal]
family = "Monofur Nerd Font"
style = "Regular"

[window]
padding = { x = 20, y = 20 }
opacity = 0.8

[colors]
transparent_background_colors = true
